DELETE http://localhost:3001/api/persons/2

###
POST http://localhost:3001/api/persons 
Content-Type: application/json

{
    "name": "Ada Lovelaceeeee",
    "number": "123"
}

###

GET http://localhost:3001/api/persons 